#!/usr/bin/env node
// Data for the Endless Echoes promo: the map (positions, routes, flowers,
// chords) from data/music-riddle.json without titles or clues, and the QR
// codes for the game's address. The hidden epilogue is left out on purpose.
import { readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const QRCode = require('qrcode');
const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '../..');

const data = JSON.parse(await readFile(path.join(root, 'data/music-riddle.json'), 'utf8'));
const nodes = data.nodes
  .filter(n => n.id !== data.bonus)
  .map(n => ({
    id: n.id,
    x: n.position[0],
    y: n.position[1],
    flower: n.presentation.flower,
    midi: n.presentation.chord.midi,
    next: n.next.filter(id => id !== data.bonus),
    terminal: n.terminal || null,
  }));
const URL_BASE = 'https://simoncos.github.io/gallery/music/endless-echoes.html';
const qr = {};
for (const lang of ['zh', 'en']) {
  const url = `${URL_BASE}?lang=${lang}`;
  const code = QRCode.create(url, { errorCorrectionLevel: 'M' });
  const size = code.modules.size;
  const rows = [];
  for (let y = 0; y < size; y++) {
    let row = '';
    for (let x = 0; x < size; x++) row += code.modules.get(x, y) ? '1' : '0';
    rows.push(row);
  }
  qr[lang] = { url, rows };
}
const out = {
  map: { width: data.map.width, height: data.map.height, routes: data.map.routes },
  start: data.start,
  ending: data.ending,
  nodes,
  qr,
};
await writeFile(path.join(here, 'data.js'), `// Generated by prep.mjs from data/music-riddle.json. Do not edit.\nwindow.ECHOES = ${JSON.stringify(out)};\n`);
console.log(`${nodes.length} nodes, ${nodes.reduce((s, n) => s + n.next.length, 0)} routes, QR ${qr.zh.rows.length} modules`);
