#!/usr/bin/env python3
"""Narration for the Simpson film, read by Kokoro (open source, Apache 2.0).

Reads lines.<lang>.json, synthesises each line, and fits the film to the
voice: every line owns a window of scene time [a, b], which is stretched or
squeezed so the line fits with some air, while the gaps between lines keep
their length. Writes

  voice.<lang>.js    window.VOICE: the warp (scene time ↔ film time), the
                     lines with their film times, and the film's duration;
                     the scene loads it to draw in film time.
  voice.<lang>.json  the same, for score.py.
  ../out/voice.<lang>.wav   the narration placed on the film's clock.

Kokoro's model files come from github.com/thewh1teagle/kokoro-onnx (releases,
model-files-v1.0); set KOKORO_DIR to the folder holding kokoro-v1.0.onnx and
voices-v1.0.bin. Needs: pip install kokoro-onnx soundfile "misaki[zh]".

    python films/simpsons/voice/voice.py zh
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from pathlib import Path

import numpy as np
import soundfile as sf

HERE = Path(__file__).resolve().parent
SCENE_DURATION = 158.0
LEAD = 0.3          # the voice starts this long after its caption appears
AIR = 0.55          # and leaves this much before the window closes
MIN_STRETCH = 0.7   # a window may shrink to 70% of its scene length, no more
# The Chinese G2P passes Latin letters through untouched, and the model then
# swallows them. Spell them as Mandarin speakers say them.
LETTERS = {"A": "ei→", "B": "pi→"}


def main() -> None:
    lang = sys.argv[1] if len(sys.argv) > 1 else "zh"
    spec = json.loads((HERE / f"lines.{lang}.json").read_text())
    from kokoro_onnx import Kokoro

    kdir = Path(os.environ.get("KOKORO_DIR", "/home/user/tts"))
    kokoro = Kokoro(str(kdir / "kokoro-v1.0.onnx"), str(kdir / "voices-v1.0.bin"))
    g2p = None
    if lang == "zh":
        from misaki import zh
        g2p = zh.ZHG2P()

    clips, rate = [], 24000
    for line in spec["lines"]:
        if g2p:
            phonemes, _ = g2p(line["say"])
            phonemes = re.sub(r"(?<![A-Za-z])([AB])(?![A-Za-z])", lambda m: LETTERS[m.group(1)], phonemes)
            audio, rate = kokoro.create(phonemes, voice=spec["voice"], speed=spec.get("speed", 1.0), is_phonemes=True)
        else:
            audio, rate = kokoro.create(line["say"], voice=spec["voice"], speed=spec.get("speed", 1.0), lang="en-us")
        # trim the model's leading and trailing silence
        idx = np.flatnonzero(np.abs(audio) > 0.01)
        audio = audio[max(0, idx[0] - int(0.03 * rate)) : idx[-1] + int(0.08 * rate)] if len(idx) else audio
        clips.append(audio.astype(np.float32))

    # the warp: scene time → film time
    warp = [[0.0, 0.0]]
    s_prev = f_prev = 0.0
    out_lines = []
    for line, clip in zip(spec["lines"], clips):
        d = len(clip) / rate
        a, b = line["a"], line["b"]
        fa = f_prev + max(0.0, a - s_prev)
        fb = fa + max(LEAD + d + AIR, MIN_STRETCH * (b - a))
        warp += [[a, round(fa, 4)], [b, round(fb, 4)]]
        out_lines.append({**line, "fa": round(fa, 4), "fb": round(fb, 4), "voice_at": round(fa + LEAD, 4), "voice_len": round(d, 4)})
        s_prev, f_prev = b, fb
    duration = round(f_prev + (SCENE_DURATION - s_prev), 3)
    warp.append([SCENE_DURATION, duration])

    data = {"lang": lang, "voice": spec["voice"], "duration": duration, "warp": warp, "lines": out_lines}
    (HERE / f"voice.{lang}.json").write_text(json.dumps(data, ensure_ascii=False, indent=1))
    (HERE / f"voice.{lang}.js").write_text(f"// Generated by voice.py. Do not edit.\nwindow.VOICE = {json.dumps(data, ensure_ascii=False)};\n")

    # the narration on the film's clock
    track = np.zeros(int((duration + 1) * rate), dtype=np.float32)
    for line, clip in zip(out_lines, clips):
        i = int(line["voice_at"] * rate)
        track[i : i + len(clip)] += clip[: len(track) - i]
    out = HERE.parent / "out"
    out.mkdir(exist_ok=True)
    tmp = out / f"voice.{lang}.24k.wav"
    sf.write(tmp, track, rate)
    subprocess.run(["ffmpeg", "-nostdin", "-loglevel", "error", "-y", "-i", str(tmp), "-ar", "48000", "-ac", "2", str(out / f"voice.{lang}.wav")], check=True)
    tmp.unlink()
    print(f"{len(out_lines)} lines, film {duration:.1f} s (scene {SCENE_DURATION} s)")
    for l in out_lines:
        k = (l["fb"] - l["fa"]) / (l["b"] - l["a"])
        print(f"  {l['a']:6.1f}–{l['b']:6.1f} → {l['fa']:6.1f}–{l['fb']:6.1f}  ×{k:.2f}  voice {l['voice_len']:.1f}s  {l['say'][:18]}")


if __name__ == "__main__":
    main()
