// Existing labels, preserved per language. Research data stays shared.
export const english = document.documentElement.lang.startsWith("en");
const zh = {
  penaltyMagnitude: "惩罚幅度",
  sleepCycleRawScore: "SleepCycle 原始分",
  rawScore: "%{x}<br>原始分: %{y:.1f}%<extra></extra>",
  moodAdjustedScore: "mood 修正分",
  moodAdjustedScore2: "%{x}<br>mood 修正分: %{y:.1f}<extra></extra>",
  fullyAdjustedScore: "完整修正分",
  fullyAdjustedScore2: "%{x}<br>完整修正分: %{y:.1f}<extra></extra>",
  sleepHEffectiveSleep: "sleep_h（有效睡眠）",
  score0100: "分数（0–100）",
  influenzaB: "乙流",
  cOVID1st: "COVID 首次",
  gapWidening: "裂口扩大",
  cOVID2nd: "COVID二次",
  influenzaA: "甲流",
  shower: "洗澡",
  noonNap: "午睡",
  holidayNight: "假日夜晚",
  workedOut: "锻炼",
  vacation: "休假",
  tired: "疲劳",
  noNightGaming1am: "非夜游\n≤1am",
  noNightGaming1am2: "非夜游\n>1am",
  nightGaming1am: "夜游\n≤1am",
  nightGaming1am2: "夜游\n>1am",
  nightGaming1am7h: "夜游\n>1am\n<7h",
  annualFrequency: "年度出现频率（%）",
  qualityComparisonAlcoholVsCaffeineVsBaseline: "有/无该物质的质量对比",
  alcohol: "酒精",
  caffeineTeaCoffee: "咖啡因（茶/咖啡）",
  frequency: "出现率 %",
  dataThroughMarSpikeLikelyDrivenBy: "* 数据截至 3 月，且集中在春节假期，不代表全年趋势",
  neither: "两者皆无",
  quality: "%{x}<br>质量: %{y:.1f}%<extra></extra>",
  avgSleepQuality: "平均睡眠质量 %",
  alcoholLateNight: "酒精 + 熬夜",
  alcoholOnlyEarly: "仅酒精（不熬夜）",
  baseline833: "基线 83.3%",
  annualHPFeelingCount: "每年 HP feeling 出现次数",
  hPFeelingTimes: "%{x}年<br>HP feeling: %{y} 次<extra></extra>",
  count: "出现次数",
  year: "年份",
  coOccurringSignalsWithMysteriousEvents: "与神秘事件一起出现的状态信号",
  nightGamingLateSleepShortBedTime: "夜游 × 晚睡 × 短卧床的叠加代价",
  sleepQualityWithVsWithoutEvent: "有/无该事件夜晚的质量对比",
  annualFrequency2: "年度出现率 %",
  qualityOnEventNights: "该事件夜晚质量",
  annualBaseline: "年度基线",
  sleepQuality: "睡眠质量 %",
  coOccurrenceLiftWithMysteriousEventsPp: "%{y}<br>与神秘事件共现抬升: %{x:.1f}pp<extra></extra>",
  moreCommonOnMysteriousEventNightsPercentage: "在有神秘事件夜晚中更常出现（百分点）",
  bad: "Bad 比例",
  bad2: "Bad 比例 %",
  withEvent: "有该事件",
  withoutEvent: "无该事件",
  breakNight: "break 占比",
  qualityDeltaVsNonBreak: "相对非 break 质量差值",
  breakNight2: "break 占比 %",
  qualityDelta: "质量差值",
  sleepQualityDelta: "睡眠质量差值",
  badMoodDelta: "Bad 比例差值",
  awakeTimeDeltaHours: "醒着时间差值（小时）",
  efficiencyDeltaPp: "效率差值（百分点）",
  movementFreqDelta: "动作频率差值",
  breakVsNonBreakDelta: "break 相对非 break 的差值",
  label20201130PostYubengTrekNight: "2020-11-30\n雨崩归来夜",
  label20251003PostHabaTrekNight: "2025-10-03\n哈巴归来夜",
  sleepQuality2: "睡眠质量",
  awakeTimeHours: "醒着时间（小时）",
  efficiency: "效率 %",
  actualSleepSleepH: "实际睡眠 (sleep_h)",
  after1AM: "过凌晨1点 %",
  after1AM2: "%{x}<br>过凌晨1点: %{y:.1f}%<extra></extra>",
  shortSleep6h: "短睡（<6h）%",
  shortSleep: "%{x}<br>短睡: %{y:.1f}%<extra></extra>",
  scheduleRegularity: "作息规律性 %",
  scheduleRegularity2: "%{x}<br>作息规律性: %{y:.1f}%<extra></extra>",
  sleepHHours: "sleep_h（小时）",
  label: "占比 (%)",
  lockdownPeak78h37Over8h: "封控高峰<br>7.8h / 37%超8h",
  label29OfNightsUnder6Hours: "29%夜晚<br>不足6小时",
  annualBedtimeMedian: "当年入睡中位数",
  median: "%{y}年 中位数: %{x}<extra></extra>",
  count2: "次数",
  nights: "%{y}年 %{x}<br>%{z} 次<extra></extra>",
  bedtime: "入睡时间",
  quality2: "质量%",
  avgQuality: "%{y}年 %{x}<br>平均质量: %{z:.1f}%<extra></extra>",
  ofNights: "夜晚占比",
  avgSleepQuality2: "平均睡眠质量",
  totalTimeInBedHours: "卧床总时长（小时）",
  label7h: "<7h 占比",
  shortNightQuality: "短夜晚质量",
  shortNightsIncreasingAfter2024: "2024 后短夜晚增多",
  good: "好",
  oK: "还行",
  bad3: "差",
  notSet: "未记录",
  label2: (v0: unknown) => `%{x}年 - ${v0}<br>%{y}%<extra></extra>`,
  badMoodTrend: "Bad 占比趋势",
  bad4: "%{x}年 Bad: %{y}%<extra></extra>",
  ofNights2: "占比 %",
  label2021JumpBad48: "2021跳变<br>Bad 48%",
  label2026Bad54DecadeHigh: "2026 Bad 54%<br>十年最高",
  snoringMin: "打呼噜（分钟）",
  breathingInterruptionTimesHr: "呼吸中断（次/小时）",
  breathingInterruption: "呼吸中断",
  badMood: "Bad 情绪比例 %",
  subjectivelyNoisy: "主观标为 Noisy %",
  earplugUseNoise: "戴耳塞抗噪 %",
  earplugs: "<b>%{x}</b><br>%{customdata}<br>耳塞: %{y:.1f}%<extra></extra>",
  quality3: "<b>%{x}</b><br>%{customdata}<br>质量: %{y:.1f}%<extra></extra>",
  frequency2: "频率 %",
  startedHighFrequencyEarplugUseNoise: "开始高频使用耳塞抗噪",
  earplugUsage: "耳塞使用率 %",
  earplugUsage2: "耳塞使用频率 %",
  sleepQuality3: "%{x}<br>睡眠质量: %{y:.1f}%<extra></extra>",
  breathingInterruptionTimesHr2: "呼吸中断: %{y:.1f} 次/小时<extra></extra>",
  targetedCardioSwimmingRingFit: "靶向心肺\n(游泳/健身环)",
  highIntensityHiking10kExercise: "高强度徒步\n(>10k+锻炼)",
  travelFatigue10kTravel: "旅行奔波\n(>10k+旅行)",
  otherHighStep10kNoTag: "其他多步数\n(>10k无标签)",
  sleepQualityDelta2: "睡眠质量差值 %",
  qualityDelta2: "%{x}<br>质量差值: %{y:.1f}%<extra></extra>",
  breathingInterruptionDeltaTimesHr: "呼吸中断差值（次/小时）",
  bDDeltaTimesHr: "BD 差值: %{y:.1f} 次/小时<extra></extra>",
  qualityDeltaVsLocalBaseline: "相对本地基线的质量差值 %",
  bedtimeDriftMin: "入睡时间偏移 (分钟)",
  bedtimeDriftMin2: "<b>%{x}</b><br>入睡时间偏移: %{y:.0f} 分钟<extra></extra>",
  sleepOnsetLatencyMin: "入睡潜伏期 (分钟)",
  sleepOnsetLatencyMin2: "<b>%{x}</b><br>入睡潜伏期: %{y:.1f} 分钟<extra></extra>",
  previousNightSleepDuration: "前一夜睡眠时长",
  label3rdDaySleepQuality: "第三日睡眠质量",
  label3rdDayQuality: "<b>%{x}</b><br>第三日质量: %{y:.1f}%<extra></extra>",
  twoConsecutiveNightsState: "连续两日睡眠状态",
  label3rdDaySleepQuality2: "第三日睡眠质量 %",
  snoringMin2: "%{x}<br>打呼噜: %{y:.1f} 分钟<extra></extra>",
  breathingInterruptionTimesHr3: "%{x}<br>呼吸中断: %{y:.2f} 次/小时<extra></extra>",
  coughTimesHr: "咳嗽（次/小时）",
  coughTimesHr2: "%{x}<br>咳嗽: %{y:.2f} 次/小时<extra></extra>",
  influenzaB202001: "乙流<br>（2020-01）",
  cOVID1st202212: "COVID 首次<br>（2022-12）",
  cOVID2nd202408: "COVID 二次<br>（2024-08）",
  influenzaA202409: "甲流<br>（2024-09）",
  sleepCycleScore: "SleepCycle 睡眠分",
  sleepScore: "%{x}<br>睡眠分: %{y:.1f}%<extra></extra>",
  hPFeelingFrequency: "HP feeling 出现率 %",
  snoringFrequency: "打呼噜出现率 %",
  snoring: "%{x}<br>打呼噜: %{y:.1f}%<extra></extra>",
  morningHeartRate: "晨起心率",
  morningHeartRate2: "%{x}<br>晨起心率: %{y:.1f}<extra></extra>",
  systemSignal: "系统信号占比 %",
  hPCuredEndOf2018: "HP 治愈<br>（2018 末）",
  startedSelfTreatingRhinitis20250415: "开始自行治疗鼻炎<br>（2025-04-15）",
  diagnosedSinusitis20250725: "确诊鼻窦炎<br>（2025-07-25）",
  monthlyAverage: "月度均值",
  label3MonthSmoothed: "3个月平滑",
  smoothed: "%{x}<br>%{y:.1f}%（平滑）<extra></extra>",
  allYears: "全部年份",
  actualSleepDurationHours: "实际睡眠时长（小时）",
  teaCoffee: "茶/咖啡",
  break: "休假",
  thinking: "睡前思考",
  afterMidnight: "过了午夜",
  earplugs2: "耳塞",
  hPFeeling: "肠胃不适(HP)",
  sick: "生病",
  stressfulDay: "压力大",
  ateLate: "吃得晚",
  nightGaming: "夜间游戏",
  music: "听音乐",
  meditation: "冥想",
  massage: "按摩",
  mysteriousEvents: "神秘事件",
  alcohol2: "饮酒",
  travel: "旅行",
  shower2: "睡前洗澡",
  holidayNight2: "无闹钟之夜",
  preSleepSad: "睡前负面情绪",
  gutUneasy: "肠道未排空",
  deltaWithTagWithoutTagN: "%{y}<br>差值: %{x:.1f}%<br>有该 tag: %{customdata[0]:.1f}%<br>无该 tag: %{customdata[1]:.1f}%<br>样本数: %{customdata[2]}<extra></extra>",
  qualityDeltaVsOverallBaseline: "相对整体基线的质量差值",
  vsBaselineAvgQualityNights: "%{x}<br>相对基线: %{y:+.1f}%<br>平均质量: %{customdata[0]:.1f}%<br>夜晚数: %{customdata[1]}<extra></extra>",
  qualityDeltaVsBaseline: "相对基线的质量差值 (%)",
  bedtimeWindow: "入睡时间段",
  badMorningMood: "Bad 晨起情绪",
  morningMood: "早晨情绪占比 (%)",
  sleepQualityRange: "睡眠质量区间",
  regularityRaw: "规律性（原始）",
  regularityRaw2: "%{x}<br>规律性（原始）: %{y:.1f}%<extra></extra>",
  scheduleRegularity3moAvg: "作息规律性（3月均）",
  regularityAvg: "%{x}<br>规律性（均）: %{y:.1f}%<extra></extra>",
  sleepCycleQualityScore3moAvg: "SleepCycle 质量分（3月均）",
  qualityAvg: "%{x}<br>质量（均）: %{y:.1f}%<extra></extra>",
  scheduleRegularity3: "作息规律性 (%)",
  sleepQuality4: "睡眠质量 (%)",
  month: "月份",
  lockdownPeak93: "封控期峰值 93%",
  afterCOVID1stScheduleRegularityBeganDeclining: "COVID 首次后<br>规律性开始持续下滑",
  travelNights: "出行夜晚",
  travelNightRate: "<b>%{y}</b><br>出行夜晚出现率: %{x:.1f}%<extra></extra>",
  baselineRate: "<b>%{y}</b><br>Baseline 出现率: %{x:.1f}%<extra></extra>",
  occurrenceRate: "出现率 (%)",
  shortTrip12Nights: "短途（1-2 晚）",
  quality4: "<b>%{x}</b><br>质量: %{y:.1f}%<extra></extra>",
  longTrip3Nights: "长途（3+ 晚）",
  homecomingRebound: "回家反弹峰值",
  qualityN: "<b>%{x}</b><br>质量: %{y:.1f}%<br>样本数: %{customdata}<extra></extra>",
  tripLength: "旅行长度",
  lateBedtime: "晚睡时点",
  nightInterruption: "夜间中断",
  lateBedtimeTired: "晚睡 × tired",
  teaCoffee2: "茶 / 咖啡",
  noAlarmNextDay: "无闹钟之夜",
  steps: "步数",
  recentVolatility: "近期波动",
  tagCount: "标签数量",
  afterMidnight2: "过午夜",
  recent7DayQuality: "近 7 天质量",
  bedtimeBucket: "入睡时段",
  yesterdayInBedTime: "昨晚卧床时长",
  bedtime2hEarlier: "提前 2 小时入睡",
  bedtime1hEarlier: "提前 1 小时入睡",
  noAlarmVsAlarm: "无闹钟 vs 有闹钟",
  massage2: "按摩",
  shower3: "洗澡",
  bedtime1hLater: "推迟 1 小时入睡",
  tired2: "tired",
  nightGaming2: "夜间游戏",
  sleepQuality5: "睡眠质量",
  sleepQuality6: "%{y}<br>睡眠质量: %{x:.0f}<extra></extra>",
  wakeUpMood: "起床情绪",
  wakeUpMood2: "%{y}<br>起床情绪: %{x:.0f}<extra></extra>",
  relativeWeightTopFactor100: "相对权重（第一名 = 100）",
  naiveAssociation: "单变量直觉",
  naivePp: "%{x}<br>直觉关联: %{y:.1f}pp<extra></extra>",
  afterControlSHAP: "控制变量后（SHAP）",
  controlledPp: "%{x}<br>控制后: %{y:.2f}pp<extra></extra>",
  impactOnOKMoodProbabilityPp: "对 OK mood 概率的影响（pp）",
  predictedChangeInSleepQualityPoints: "对睡眠质量的预测变化（分）",
  predictedChangeInOKMoodProbabilityPp: "对 OK mood 概率的预测变化（pp）",
};
const en = {
  penaltyMagnitude: "Penalty magnitude",
  sleepCycleRawScore: "SleepCycle Raw score",
  rawScore: "%{x}<br>Raw score: %{y:.1f}%<extra></extra>",
  moodAdjustedScore: "Mood-adjusted score",
  moodAdjustedScore2: "%{x}<br>Mood-adjusted score: %{y:.1f}<extra></extra>",
  fullyAdjustedScore: "Fully-adjusted score",
  fullyAdjustedScore2: "%{x}<br>Fully-adjusted score: %{y:.1f}<extra></extra>",
  sleepHEffectiveSleep: "sleep_h (effective sleep)",
  score0100: "Score (0–100)",
  influenzaB: "Influenza B",
  cOVID1st: "COVID (1st)",
  gapWidening: "Gap widening",
  cOVID2nd: "COVID (2nd)",
  influenzaA: "Influenza A",
  shower: "shower",
  noonNap: "noon nap",
  holidayNight: "holiday night",
  workedOut: "Worked out",
  vacation: "Vacation",
  tired: "tired",
  noNightGaming1am: "No night gaming\n≤1am",
  noNightGaming1am2: "No night gaming\n>1am",
  nightGaming1am: "Night gaming\n≤1am",
  nightGaming1am2: "Night gaming\n>1am",
  nightGaming1am7h: "Night gaming\n>1am\n<7h",
  annualFrequency: "Annual frequency (%)",
  qualityComparisonAlcoholVsCaffeineVsBaseline: "Quality comparison: alcohol vs caffeine vs baseline",
  alcohol: "Alcohol",
  caffeineTeaCoffee: "Caffeine (tea/coffee)",
  frequency: "Frequency %",
  dataThroughMarSpikeLikelyDrivenBy: "* data through Mar; spike likely driven by Lunar New Year holiday cluster",
  neither: "Neither",
  quality: "%{x}<br>Quality: %{y:.1f}%<extra></extra>",
  avgSleepQuality: "Avg Sleep Quality %",
  alcoholLateNight: "Alcohol + late night",
  alcoholOnlyEarly: "Alcohol only (early)",
  baseline833: "baseline 83.3%",
  annualHPFeelingCount: "Annual HP feeling count",
  hPFeelingTimes: "%{x}<br>HP feeling: %{y} times<extra></extra>",
  count: "Count",
  year: "Year",
  coOccurringSignalsWithMysteriousEvents: "Co-occurring signals with Mysterious Events",
  nightGamingLateSleepShortBedTime: "Night gaming × late sleep × short bed time — cumulative cost",
  sleepQualityWithVsWithoutEvent: "Sleep quality: with vs without event",
  annualFrequency2: "Annual frequency %",
  qualityOnEventNights: "Quality on event nights",
  annualBaseline: "Annual Baseline",
  sleepQuality: "Sleep Quality %",
  coOccurrenceLiftWithMysteriousEventsPp: "%{y}<br>Co-occurrence lift with Mysterious Events: %{x:.1f}pp<extra></extra>",
  moreCommonOnMysteriousEventNightsPercentage: "More common on Mysterious Event nights (percentage points)",
  bad: "Bad %",
  bad2: "Bad %",
  withEvent: "With event",
  withoutEvent: "Without event",
  breakNight: "Break night %",
  qualityDeltaVsNonBreak: "Quality delta vs non-break",
  breakNight2: "Break night %",
  qualityDelta: "Quality Delta",
  sleepQualityDelta: "Sleep quality delta",
  badMoodDelta: "Bad mood % delta",
  awakeTimeDeltaHours: "Awake time delta (hours)",
  efficiencyDeltaPp: "Efficiency delta (pp)",
  movementFreqDelta: "Movement freq delta",
  breakVsNonBreakDelta: "Break vs non-break delta",
  label20201130PostYubengTrekNight: "2020-11-30\nPost-Yubeng trek night",
  label20251003PostHabaTrekNight: "2025-10-03\nPost-Haba trek night",
  sleepQuality2: "Sleep Quality",
  awakeTimeHours: "Awake time (hours)",
  efficiency: "Efficiency %",
  actualSleepSleepH: "Actual sleep (sleep_h)",
  after1AM: "After 1AM %",
  after1AM2: "%{x}<br>After 1AM: %{y:.1f}%<extra></extra>",
  shortSleep6h: "Short sleep (<6h) %",
  shortSleep: "%{x}<br>Short sleep: %{y:.1f}%<extra></extra>",
  scheduleRegularity: "Schedule Regularity %",
  scheduleRegularity2: "%{x}<br>Schedule Regularity: %{y:.1f}%<extra></extra>",
  sleepHHours: "sleep_h (hours)",
  label: "% (%)",
  lockdownPeak78h37Over8h: "Lockdown peak\n7.8h / 37% over 8h",
  label29OfNightsUnder6Hours: "29% of nights\nunder 6 hours",
  annualBedtimeMedian: "Annual bedtime median",
  median: "%{y} median: %{x}<extra></extra>",
  count2: "Count",
  nights: "%{y} %{x}<br>%{z} nights<extra></extra>",
  bedtime: "Bedtime",
  quality2: "Quality%",
  avgQuality: "%{y} %{x}<br>Avg quality: %{z:.1f}%<extra></extra>",
  ofNights: "% of Nights",
  avgSleepQuality2: "Avg Sleep Quality",
  totalTimeInBedHours: "Total Time in Bed (hours)",
  label7h: "<7h %",
  shortNightQuality: "Short night quality",
  shortNightsIncreasingAfter2024: "Short nights increasing after 2024",
  good: "Good",
  oK: "OK",
  bad3: "Bad",
  notSet: "Not set",
  label2: (v0: unknown) => `%{x} - ${v0}<br>%{y}%<extra></extra>`,
  badMoodTrend: "Bad mood trend",
  bad4: "%{x} Bad: %{y}%<extra></extra>",
  ofNights2: "% of Nights",
  label2021JumpBad48: "2021 jump\nBad 48%",
  label2026Bad54DecadeHigh: "2026 Bad 54%\ndecade high",
  snoringMin: "Snoring (min)",
  breathingInterruptionTimesHr: "Breathing Interruption (times/hr)",
  breathingInterruption: "Breathing Interruption",
  badMood: "Bad mood %",
  subjectivelyNoisy: "Subjectively noisy %",
  earplugUseNoise: "Earplug use (noise) %",
  earplugs: "<b>%{x}</b><br>%{customdata}<br>Earplugs: %{y:.1f}%<extra></extra>",
  quality3: "<b>%{x}</b><br>%{customdata}<br>Quality: %{y:.1f}%<extra></extra>",
  frequency2: "Frequency %",
  startedHighFrequencyEarplugUseNoise: "Started high-frequency earplug use (noise)",
  earplugUsage: "Earplug Usage %",
  earplugUsage2: "Earplug Usage %",
  sleepQuality3: "%{x}<br>Sleep Quality: %{y:.1f}%<extra></extra>",
  breathingInterruptionTimesHr2: "Breathing Interruption: %{y:.1f} times/hr<extra></extra>",
  targetedCardioSwimmingRingFit: "Targeted cardio\n(Swimming/Ring Fit)",
  highIntensityHiking10kExercise: "High-intensity hiking\n(>10k+exercise)",
  travelFatigue10kTravel: "Travel fatigue\n(>10k+travel)",
  otherHighStep10kNoTag: "Other high-step\n(>10k no tag)",
  sleepQualityDelta2: "Sleep quality delta %",
  qualityDelta2: "%{x}<br>Quality delta: %{y:.1f}%<extra></extra>",
  breathingInterruptionDeltaTimesHr: "Breathing Interruption delta (times/hr)",
  bDDeltaTimesHr: "BD delta: %{y:.1f} times/hr<extra></extra>",
  qualityDeltaVsLocalBaseline: "Quality delta vs local baseline %",
  bedtimeDriftMin: "Bedtime Drift (min)",
  bedtimeDriftMin2: "<b>%{x}</b><br>Bedtime Drift: %{y:.0f} min<extra></extra>",
  sleepOnsetLatencyMin: "Sleep Onset Latency (min)",
  sleepOnsetLatencyMin2: "<b>%{x}</b><br>Sleep Onset Latency: %{y:.1f} min<extra></extra>",
  previousNightSleepDuration: "Previous night sleep duration",
  label3rdDaySleepQuality: "3rd Day Sleep Quality",
  label3rdDayQuality: "<b>%{x}</b><br>3rd Day Quality: %{y:.1f}%<extra></extra>",
  twoConsecutiveNightsState: "Two consecutive nights state",
  label3rdDaySleepQuality2: "3rd Day Sleep Quality %",
  snoringMin2: "%{x}<br>Snoring: %{y:.1f} min<extra></extra>",
  breathingInterruptionTimesHr3: "%{x}<br>Breathing Interruption: %{y:.2f} times/hr<extra></extra>",
  coughTimesHr: "Cough (times/hr)",
  coughTimesHr2: "%{x}<br>Cough: %{y:.2f} times/hr<extra></extra>",
  influenzaB202001: "Influenza B<br>(2020-01)",
  cOVID1st202212: "COVID (1st)<br>(2022-12)",
  cOVID2nd202408: "COVID (2nd)<br>(2024-08)",
  influenzaA202409: "Influenza A<br>(2024-09)",
  sleepCycleScore: "SleepCycle score",
  sleepScore: "%{x}<br>Sleep score: %{y:.1f}%<extra></extra>",
  hPFeelingFrequency: "HP feeling frequency %",
  snoringFrequency: "Snoring frequency %",
  snoring: "%{x}<br>Snoring: %{y:.1f}%<extra></extra>",
  morningHeartRate: "Morning heart rate",
  morningHeartRate2: "%{x}<br>Morning heart rate: %{y:.1f}<extra></extra>",
  systemSignal: "System signal %",
  hPCuredEndOf2018: "HP Cured<br>(end of 2018)",
  startedSelfTreatingRhinitis20250415: "Started self-treating rhinitis<br>(2025-04-15)",
  diagnosedSinusitis20250725: "Diagnosed sinusitis<br>(2025-07-25)",
  monthlyAverage: "Monthly Average",
  label3MonthSmoothed: "3-month smoothed",
  smoothed: "%{x}<br>%{y:.1f}% (smoothed)<extra></extra>",
  allYears: "All Years",
  actualSleepDurationHours: "Actual Sleep Duration (hours)",
  teaCoffee: "tea/coffee",
  break: "break",
  thinking: "thinking",
  afterMidnight: "after midnight",
  earplugs2: "Earplugs",
  hPFeeling: "HP feeling",
  sick: "sick",
  stressfulDay: "Stressful day",
  ateLate: "Ate late",
  nightGaming: "night gaming",
  music: "music",
  meditation: "meditation",
  massage: "massage",
  mysteriousEvents: "Mysterious Events",
  alcohol2: "Alcohol",
  travel: "travel",
  shower2: "shower",
  holidayNight2: "holiday night",
  preSleepSad: "pre-sleep sad",
  gutUneasy: "gut uneasy",
  deltaWithTagWithoutTagN: "%{y}<br>delta: %{x:.1f}%<br>With tag: %{customdata[0]:.1f}%<br>Without tag: %{customdata[1]:.1f}%<br>n: %{customdata[2]}<extra></extra>",
  qualityDeltaVsOverallBaseline: "Quality delta vs overall baseline",
  vsBaselineAvgQualityNights: "%{x}<br>vs baseline: %{y:+.1f}%<br>Avg quality: %{customdata[0]:.1f}%<br>Nights: %{customdata[1]}<extra></extra>",
  qualityDeltaVsBaseline: "Quality delta vs baseline (%)",
  bedtimeWindow: "Bedtime window",
  badMorningMood: "Bad morning mood",
  morningMood: "Morning mood % (%)",
  sleepQualityRange: "Sleep quality range",
  regularityRaw: "Regularity (raw)",
  regularityRaw2: "%{x}<br>Regularity (raw): %{y:.1f}%<extra></extra>",
  scheduleRegularity3moAvg: "Schedule Regularity (3mo avg)",
  regularityAvg: "%{x}<br>Regularity (avg): %{y:.1f}%<extra></extra>",
  sleepCycleQualityScore3moAvg: "SleepCycle quality score (3mo avg)",
  qualityAvg: "%{x}<br>Quality (avg): %{y:.1f}%<extra></extra>",
  scheduleRegularity3: "Schedule Regularity (%)",
  sleepQuality4: "Sleep Quality (%)",
  month: "Month",
  lockdownPeak93: "Lockdown peak 93%",
  afterCOVID1stScheduleRegularityBeganDeclining: "After COVID (1st)\nSchedule regularity began declining",
  travelNights: "Travel nights",
  travelNightRate: "<b>%{y}</b><br>Travel night rate: %{x:.1f}%<extra></extra>",
  baselineRate: "<b>%{y}</b><br>Baseline rate: %{x:.1f}%<extra></extra>",
  occurrenceRate: "Occurrence Rate (%)",
  shortTrip12Nights: "Short trip (1–2 nights)",
  quality4: "<b>%{x}</b><br>Quality: %{y:.1f}%<extra></extra>",
  longTrip3Nights: "Long trip (3+ nights)",
  homecomingRebound: "Homecoming rebound",
  qualityN: "<b>%{x}</b><br>Quality: %{y:.1f}%<br>n: %{customdata}<extra></extra>",
  tripLength: "Trip Length",
  lateBedtime: "Late bedtime",
  nightInterruption: "Night interruption",
  lateBedtimeTired: "Late bedtime × tired",
  teaCoffee2: "Tea / coffee",
  noAlarmNextDay: "No alarm next day",
  steps: "Steps",
  recentVolatility: "Recent volatility",
  tagCount: "Tag count",
  afterMidnight2: "After midnight",
  recent7DayQuality: "Recent 7-day quality",
  bedtimeBucket: "Bedtime bucket",
  yesterdayInBedTime: "Yesterday in-bed time",
  bedtime2hEarlier: "Bedtime 2h earlier",
  bedtime1hEarlier: "Bedtime 1h earlier",
  noAlarmVsAlarm: "No alarm vs alarm",
  massage2: "Massage",
  shower3: "Shower",
  bedtime1hLater: "Bedtime 1h later",
  tired2: "Tired",
  nightGaming2: "Night gaming",
  sleepQuality5: "Sleep quality",
  sleepQuality6: "%{y}<br>Sleep quality: %{x:.0f}<extra></extra>",
  wakeUpMood: "Wake-up mood",
  wakeUpMood2: "%{y}<br>Wake-up mood: %{x:.0f}<extra></extra>",
  relativeWeightTopFactor100: "Relative weight (top factor = 100)",
  naiveAssociation: "Naive association",
  naivePp: "%{x}<br>Naive: %{y:.1f}pp<extra></extra>",
  afterControlSHAP: "After control (SHAP)",
  controlledPp: "%{x}<br>Controlled: %{y:.2f}pp<extra></extra>",
  impactOnOKMoodProbabilityPp: "Impact on OK-mood probability (pp)",
  predictedChangeInSleepQualityPoints: "Predicted change in sleep quality (points)",
  predictedChangeInOKMoodProbabilityPp: "Predicted change in OK-mood probability (pp)",
};
export const copy = english ? en : zh;
const tags: Record<string, string> = {
    '洗澡': 'shower', '午睡': 'noon nap', '假日夜晚': 'holiday night',
    '锻炼': 'Worked out', '休假': 'Vacation', '疲劳': 'tired',
    '生病': 'sick', '夜间游戏': 'night gaming', '神秘事件': 'Mysterious Events',
    '旅行': 'travel', '饮酒': 'Alcohol', '冥想': 'meditation',
    '按摩': 'massage', '耳塞': 'Earplugs', '过了午夜': 'after midnight',
    '压力大': 'Stressful day', '吃得晚': 'Ate late', '睡前思考': 'thinking',
    '睡前负面情绪': 'pre-sleep sad', '肠道未排空': 'gut uneasy',
    '茶/咖啡': 'tea/coffee', 'HP feeling': 'HP feeling',
  };
const environment: Record<string, string> = {...{
    '10–18°C (偏冷)': '10–18°C (Cool)',
    '18–24°C (适宜)': '18–24°C (Comfortable)',
    '>24°C (偏热)': '>24°C (Warm)'
  }, ...{
    '晴/多云 (Clear/Cloudy)': 'Clear/Cloudy',
    '雨天 (Rain/Wet)': 'Rainy/Wet'
  }};
export const remapTag = (tag: string) => english ? tags[tag] || tag : tag;
export const remapEnvironmentLabel = (label: string) => english ? environment[label] || label : label;
